version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/demos/strava-explorer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/demos/aqi-map"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/demos/isochrones"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/demos/hairstyle-ai-studio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
